SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `recaplas`;

CREATE TABLE IF NOT EXISTS recaplas.`LAS_REQUEST_ITEM_T` (
  `LAS_REQUEST_ITEM_ID` INT NOT NULL AUTO_INCREMENT,
  `SCSB_REQUEST_ID` INT NOT NULL,
  `BARCODE` VARCHAR(45) NOT NULL,
  `REQUEST_STATUS_CODE` VARCHAR(45) NOT NULL,
  `CREATED_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`LAS_REQUEST_ITEM_ID`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS recaplas.`LAS_ITEM_T` (
  `LAS_ITEM_ID` INT NOT NULL AUTO_INCREMENT,
  `BARCODE` VARCHAR(45) NOT NULL,
  `STATUS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`LAS_ITEM_ID`)
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
