FROM recapscsb/scsb-base:latest
MAINTAINER HTC ReCAP Support "recap-support@htcindia.com"

#Install Solr
RUN curl https://downloads.apache.org/lucene/solr/8.5.1/solr-8.5.1.tgz | tar -C /opt/ --extract --gzip