#FROM recapscsb/scsb-base:latest
FROM phase4-scsb-base:latest
MAINTAINER HTC ReCAP Support "recap-support@htcindia.com"

#Install Solr
RUN curl http://archive.apache.org/dist/lucene/solr/8.5.1/solr-8.5.1.tgz | tar -C /opt/ --extract --gzip